# Generated by Django 4.0.5 on 2022-06-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('starting_bid', models.IntegerField()),
                ('imgage', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
