# Generated by Django 4.0.5 on 2022-06-13 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
