# Generated by Django 4.0.5 on 2022-06-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_ammount',
            new_name='bid_amount',
        ),
    ]
