# Generated by Django 4.0.5 on 2022-06-23 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_bid_ammount_bid_bid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted', to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_watching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
