# Generated by Django 4.0.5 on 2022-06-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='amount',
        ),
    ]
