# Generated by Django 4.0.5 on 2022-06-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_bid_amount_bid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing_key',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_key',
            new_name='listing',
        ),
    ]
